spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/fit?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false

    redis:
      host: localhost
      port: 6379

# ===== 개발용 로깅 =====
logging:
  level:
    com.back: DEBUG
    org.hibernate.orm.jdbc.bind: DEBUG

# ===== OpenAPI 스키마 생성 설정 (개발환경) =====
openapi:
  schema:
    enabled: true
