spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/db_project2
    username: root
    password: root123414
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false