server:
  forward-headers-strategy: native

spring:
  application:
    name: back
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev
    include: secret
  output:
    ansi:
      enabled: always
  datasource:
    hikari:
      auto-commit: false
  jackson:
    serialization:
      fail-on-empty-beans: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL__SENDER__EMAIL}
    password: ${GMAIL__SENDER__PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

custom:
  jwt:
    secretKey: ${CUSTOM__JWT__SECRET_KEY}
  accessToken:
    expireSeconds: "#{60 * 15}"
