spring:
  application:
    name: back
  profiles:
    active: dev
    include: secret
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
