version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: fit_db
      MYSQL_USER: fit_user
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fit_db?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: fit_user
      SPRING_DATASOURCE_PASSWORD: your_password
    ports:
      - "8080:8080"

volumes:
  db-data: